name: Coverage Validation

on:
  pull_request:
    branches:
      - main  # Substitua 'main' pela branch principal do seu repositório

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run Tests
        run: |
          bundle exec rspec
      - name: Validate Coverage
        run: |
          export COVERAGE_FILE=./coverage/.resultset.json
          gem install simplecov
          simplecov check coverage: 100
