name: Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests and Generate Coverage Report
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:schema:load RAILS_ENV=test
          bundle exec rspec --format json --out coverage/rspec_coverage.json

      - name: Process Coverage Report
        id: coverage
        run: |
          COVERAGE_JSON=$(cat coverage/rspec_coverage.json)
          COVERAGE_TOTAL=$(echo "$COVERAGE_JSON" | jq '[.examples[].covered_percent] | add / length')
          echo "Cobertura de código total: $COVERAGE_TOTAL"
          echo "COVERAGE_TOTAL=$COVERAGE_TOTAL" >> $GITHUB_ENV

      - name: Validate Coverage
        run: |
          export COVERAGE_FILE=./coverage/.resultset.json
          gem install simplecov
          simplecov check coverage: 100

      - name: Upload Coverage Report
        if: success()  # Upload the report only if the previous step succeeds
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage

      - name: Comment Coverage on Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        uses: unsplash/comment-on-pr@v1
        with:
          message: "Cobertura de código: ${{ env.COVERAGE_TOTAL }}%"
