name: Coverage Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests
        run: |
          bundle exec rspec

      - name: Validate Coverage
        run: |
          export COVERAGE_FILE=./coverage/.resultset.json

          gem install simplecov

          # Gere o relatório de cobertura usando SimpleCov em formato JSON
          bundle exec rspec --format json --out coverage/rspec_coverage.json

          # Extraia o resultado da cobertura do arquivo gerado pelo RSpec
          COVERAGE=$(cat coverage/rspec_coverage.json | jq '.coverage.total')

          # Exiba a cobertura alcançada
          echo "Cobertura de código: $COVERAGE"

          # Determine se a cobertura atende aos critérios de sucesso ou falha
          if (( $(echo "$COVERAGE >= 100" | bc -l) )); then
            echo "Cobertura de código atende aos critérios de sucesso."
          else
            echo "Cobertura de código não atende aos critérios de sucesso."
            exit 1 # Falha
          fi
