name: Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:schema:load RAILS_ENV=test
          bundle exec rspec

      - name: Extract Coverage Percentage And Add Coverage Comment
        run: |
          sudo apt-get update
          sudo apt-get -y install jq

          coverage_percentage=$(jq -r '.result.line' coverage/.last_run.json)

          echo "Coverage Percentage: $coverage_percentage%"

          message="Coverage Percentage: $coverage_percentage%"

          pull_request_number=$(echo "$GITHUB_REF" | awk -F/ '{print $3}')

          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d "{\"body\":\"$message\"}" "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$pull_request_number/comments"
