name: Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    name: RuboCop Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run RuboCop
        run: bundle exec rubocop
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
        issues: write
        pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:schema:load RAILS_ENV=test
          bundle exec rspec

      - name: Extract Coverage Percentage
        run: |
          sudo apt-get update
          sudo apt-get -y install jq

          coverage_percentage=$(jq -r '.result.line' coverage/.last_run.json)

          message="Coverage Percentage: $coverage_percentage%"

          echo "MESSAGE=$message" >> $GITHUB_ENV

      - name: Add Coverage Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const message = process.env.MESSAGE
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })
