name: Rails CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Test and Coverage Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:schema:load RAILS_ENV=test
          bundle exec rspec

      - name: Validate Coverage
        run: |
          export COVERAGE_FILE=./coverage/.resultset.json

          gem install simplecov

          simplecov

          COVERAGE=$(simplecov_json_summary ./coverage/.resultset.json)

          echo "Cobertura de código: $COVERAGE"

          exit 0 # Sucesso
