name: Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:schema:load RAILS_ENV=test
          bundle exec rspec

      - name: Extract Coverage Percentage
        run: |
          apt-get update
          apt-get -y install grep sed

          coverage_percentage=$(grep -Eo '<h2>\s*<span class="group_name">All Files<\/span>\s*\(.*<span class="[^"]+">([0-9.]+)%<\/span>\s*<\/span>\s*\)<\/h2>' coverage/index.html | sed -E 's/<[^>]+>//g')

          echo "Coverage Percentage: $percentage%"
