name: Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests with Coverage
        env:
          CI: true # Define a variável CI para evitar que o SimpleCov crie relatórios HTML
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:schema:load RAILS_ENV=test
          bundle exec rspec --format progress --format RspecJunitFormatter --out test-results.xml
          COVERAGE=true bundle exec rspec

      - name: Display Coverage (if successful)
        if: always() && failure() != true() # Executa apenas se a etapa anterior for bem-sucedida
        run: |
          gem install simplecov
          simplecov-html -o coverage
          echo "Coverage report:"
          cat coverage/index.html

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.xml

      - name: Upload Coverage Artifact
        if: always() && failure() != true() # Executa apenas se a etapa anterior for bem-sucedida
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage
